name: Bug report
description: File a bug/issue
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the problem.
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
  - type: input
    id: version
    attributes:
      label: Version/commit
      placeholder: e.g. v0.1.0 or commit hash
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, Node.js version, package manager.
      placeholder: e.g. macOS 14, Node 20.11, npm 10
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste relevant logs or stack traces.
      render: text

